service: anagrafica

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan*
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/anagraficaUtentiTable


environment:
  DYNAMODB_UTENTI_TABLE: anagraficaUtentiTable

plugins:
  - serverless-pseudo-parameters



functions:
  create:
    handler: ./src/create/handler.create
    events:
      - http:
          path: /v1/createUtente
          method: post
  list:
    handler: ./src/read/handler.list
    events:
      - http:
          path: /v1/getAllUtenti
          method: get
  get:
    handler: ./src/read/handler.get
    events:
      - http:
          path: /v1/getUtente/{codicefiscale}
          method: get
  update:
    handler: ./src/update/handler.update
    events:
      - http:
          path: /v1/updateUtente/{codicefiscale}
          method: put
  delete:
    handler: ./src/delete/handler.delete
    events:
      - http:
          path: /v1/deleteUtente/{codicefiscale}
          method: delete

resources:
  Resources:
    anagraficaUtentiTable:
      Type: 'AWS::DynamoDB::Table'
      Properties: 
        TableName: anagraficaUtentiTable
        AttributeDefinitions: 
          - AttributeName: codicefiscale
            AttributeType: S
        KeySchema:
          - AttributeName: codicefiscale 
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST